# ---------- builder ----------
    FROM node:20-bookworm-slim AS builder
    WORKDIR /app
    RUN apt-get update -y && apt-get install -y --no-install-recommends openssl ca-certificates && rm -rf /var/lib/apt/lists/*
    
    COPY package.json package-lock.json* ./
    RUN npm install
    
    COPY . .
    RUN npx prisma generate
    RUN npm run build
    RUN npm prune --omit=dev
    
    # ---------- runner ----------
    FROM node:20-bookworm-slim AS runner
    WORKDIR /app
    ENV NODE_ENV=production
    RUN apt-get update -y && apt-get install -y --no-install-recommends openssl ca-certificates && rm -rf /var/lib/apt/lists/*
    
    COPY --from=builder /app/node_modules ./node_modules
    COPY --from=builder /app/dist ./dist
    COPY --from=builder /app/prisma ./prisma
    COPY --from=builder /app/package.json ./package.json
    
    RUN mkdir -p /app/uploads
    
    EXPOSE 4000
    
    CMD ["sh", "-c", "npx prisma migrate deploy && node dist/main.js"]